// import 'dart:io';

// void main() {
//   final directory = Directory('assets/smiles');
//   final buffer = StringBuffer();

//   buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
//   buffer.writeln('// This file is automatically generated.');
//   buffer.writeln();
//   buffer.writeln('class Assets {');
//   buffer.writeln('  Assets._();');
//   buffer.writeln();
//   buffer.writeln('  static const smiles = [');

//   directory.listSync().forEach((file) {
//     if (file is File) {
//       final fileName = file.path.split('/').last.replaceAll('\\', '/');
//       buffer.writeln("    'assets/$fileName',");
//     }
//   });

//   buffer.writeln('  ];');
//   buffer.writeln('}');

//   final outputFile = File('lib/assets_generated/generated_assets_smiles.dart');
//   outputFile.writeAsStringSync(buffer.toString());

//   //log('Asset list generated: lib/generated_assets.dart');
// }
