// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated.

import 'package:lklk/core/constants/assets.dart';
import 'package:lklk/features/profile_users/domain/entities/elements_entity.dart';

class Assets {
  Assets._();

  static const gifts = [
    'assets/gift/black car.svga',
    'assets/gift/black sport car.svga',
    'assets/gift/blue atv.svga',
    'assets/gift/blue car.svga',
    'assets/gift/bmw i8.svga',
    'assets/gift/bugatti.svga',
    'assets/gift/green lambo.svga',
    'assets/gift/purple car.svga',
    'assets/gift/red motobike.svga',
    'assets/gift/rolls royce.svga',
    'assets/gift/transformer.svga',
    'assets/gift/yellow car.svga',
  ];
  static List<ElementEntity> generateGifts() {
    return List<ElementEntity>.generate(gifts.length, (index) {
      final path = gifts[index];
      final elementName = path.split('/').last.split('.').first;
      return ElementEntity(
        id: index + 1000,
        price: "(index + 1) * 100",
        linkPath: path,
        elementName: elementName,
        imgElement: AssetsData.gift,
        type: 'popular',
      );
    });
  }
}
