// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is automatically generated.

class Assets {
  Assets._();

  static const smiles = [
    'assets/smiles/☹وجه عابس(120 x 120).gif',
    'assets/smiles/👀عينان(120 x 120).gif',
    'assets/smiles/👏يدان تصفقان(120 x 120).gif',
    'assets/smiles/👻شبح(120 x 120).gif',
    'assets/smiles/💃راقصة(120 x 120).gif',
    'assets/smiles/💣قنبلة(120 x 120).gif',
    'assets/smiles/🕺رجل يرقص(120 x 120).gif',
    'assets/smiles/😂وجه بدموع فرح(120 x 120).gif',
    'assets/smiles/😇وجه مبتسم بهالة(120 x 120).gif',
    'assets/smiles/😊وجه باسم بعينين باسمتين(120 x 120).gif',
    'assets/smiles/😋وجه يتلذذ بالطعام(120 x 120).gif',
    'assets/smiles/😎وجه مبتسم بنظارة شمس(120 x 120).gif',
    'assets/smiles/😒وجه غير مستمتع(120 x 120).gif',
    'assets/smiles/😘وجه يرسل قبلة(120 x 120).gif',
    'assets/smiles/😚وجه يقبّل بعينين مغلقتين(120 x 120).gif',
    'assets/smiles/😜وجه بلسان متدلٍ وعين غامزة(120 x 120).gif',
    'assets/smiles/😩وجه مجهد(120 x 120).gif',
    'assets/smiles/😫وجه متعب(120 x 120).gif',
    'assets/smiles/😭وجه يبكي بكاءً مرتفعًا(120 x 120).gif',
    'assets/smiles/🙄وجه بعينين تدوران(120 x 120).gif',
    'assets/smiles/🤐وجه بفم مقفل(120 x 120).gif',
    'assets/smiles/🤑وجه بلسان من مال(120 x 120).gif',
    'assets/smiles/🤓وجه عبقري(120 x 120).gif',
    'assets/smiles/🤔وجه يفكر(120 x 120).gif',
    'assets/smiles/🤗وجه يعانق بابتسامة(120 x 120).gif',
    'assets/smiles/🤤وجه بلعاب سائل(120 x 120).gif',
    'assets/smiles/🤨وجه بحاجب مرفوع(120 x 120).gif',
    'assets/smiles/🤫وجه يطلب الصمت(120 x 120).gif',
    'assets/smiles/🤭وجه ضاحك مع يد تغطّي الفم(120 x 120).gif',
    'assets/smiles/🥰وجه مبتسم مع ثلاثة قلوب(120 x 120).gif',
    'assets/smiles/🥱وجه متثائب(120 x 120).gif',
    'assets/smiles/🥳وجه محتفل(120 x 120).gif',
    'assets/smiles/🥴وجه مصاب بدوار(120 x 120).gif',
    'assets/smiles/🥺وجه ملتمس(120 x 120).gif',
    'assets/smiles/🫣وجه يختلس النظر(120 x 120).gif',
    'assets/smiles/🫶🏿أيدي متشابكة على شكل قلب_ بشرة بلون غامق(120 x 120).gif',
    'assets/smiles/so_happy.gif',
  ];
}
