import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:auto_size_text/auto_size_text.dart';
import 'package:lklk/core/utils/logger.dart';
import 'package:lklk/features/auth/domain/entities/user_entity.dart';

import '../../components/components.dart';
import '../../live_audio_room_manager.dart';
import '../../utils/zegocloud_token.dart';
import '../../zego_sdk_key_center.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:lklk/features/livekit_audio/presentation/cubit/livekit_audio_cubit.dart';
import 'package:lklk/features/livekit_audio/presentation/cubit/livekit_audio_state.dart';

part 'audio_room_gift.dart';

class AudioRoomPage extends StatefulWidget {
  const AudioRoomPage({super.key, required this.roomID, required this.role});

  final String roomID;
  final ZegoLiveAudioRoomRole role;

  @override
  State<AudioRoomPage> createState() => AudioRoomPageState();
}

class AudioRoomPageState extends State<AudioRoomPage> {
  List<StreamSubscription> subscriptions = [];
  String? currentRequestID;
  ValueNotifier<bool> isApplyStateNoti = ValueNotifier(false);

  @override
  void initState() {
    super.initState();
    final zimService = ZEGOSDKManager().zimService;
    final expressService = ZEGOSDKManager().expressService;
    subscriptions.addAll([
      expressService.roomStateChangedStreamCtrl.stream
          .listen(onExpressRoomStateChanged),
      zimService.roomStateChangedStreamCtrl.stream
          .listen(onZIMRoomStateChanged),
      zimService.connectionStateStreamCtrl.stream
          .listen(onZIMConnectionStateChanged),
      zimService.onInComingRoomRequestStreamCtrl.stream
          .listen(onInComingRoomRequest),
      // zimService.onOutgoingRoomRequestAcceptedStreamCtrl.stream
      //     .listen(onOutgoingRoomRequestAccepted),
      zimService.onOutgoingRoomRequestRejectedStreamCtrl.stream
          .listen(onOutgoingRoomRequestRejected),
    ]);

    loginRoom();

    initGift();
  }

  void loginRoom() {
    // ! ** Warning: ZegoTokenUtils is only for use during testing. When your application goes live,
    // ! ** tokens must be generated by the server side. Please do not generate tokens on the client side!
    final token = kIsWeb
        ? ZegoTokenUtils.generateToken(SDKKeyCenter.appID,
            SDKKeyCenter.serverSecret, ZEGOSDKManager().currentUser!.iduser)
        : null;
    ZegoLiveAudioRoomManager()
        .loginRoom(widget.roomID, widget.role, token: token)
        .then((result) {
      if (result.errorCode == 0) {
        // hostTakeSeat();
      } else {
        Navigator.pop(context);
      }
    });
  }

  @override
  void dispose() {
    super.dispose();
    uninitGift();
    ZegoLiveAudioRoomManager().logoutRoom();
    for (final subscription in subscriptions) {
      subscription.cancel();
    }
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      top: false,
      child: Scaffold(
        body: Stack(
          children: [
            backgroundImage(),
            Positioned(top: 30, left: 10, child: roomTitle()),
            Positioned(top: 30, right: 20, child: leaveButton()),
            Positioned(bottom: 20, left: 0, right: 0, child: bottomView()),
            giftForeground()
          ],
        ),
      ),
    );
  }

  Widget backgroundImage() {
    return Image.asset('assets/images/audio_bg.png',
        width: double.infinity, height: double.infinity, fit: BoxFit.fill);
  }

  Widget roomTitle() {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            AutoSizeText('LiveAudioRoom',
                style: Theme.of(context).textTheme.titleMedium),
            AutoSizeText('Room ID: ${widget.roomID}'),
            ValueListenableBuilder(
              valueListenable: ZegoLiveAudioRoomManager().hostUserNoti,
              builder: (BuildContext context, UserEntity? host, Widget? child) {
                return host != null
                    ? AutoSizeText('Host: ${host.name} (id: ${host.iduser})')
                    : const SizedBox.shrink();
              },
            ),
          ],
        ),
      ),
    );
  }

  Widget bottomView() {
    return ValueListenableBuilder<ZegoLiveAudioRoomRole>(
        valueListenable: ZegoLiveAudioRoomManager().roleNoti,
        builder: (context, currentRole, _) {
          if (currentRole == ZegoLiveAudioRoomRole.host) {
            return Row(
              mainAxisAlignment: MainAxisAlignment.end,
              children: [
                lockSeatButton(),
                const SizedBox(width: 10),
                requestMemberButton(),
                const SizedBox(width: 10),
                micorphoneButton(),
                const SizedBox(width: 20),
              ],
            );
          } else if (currentRole == ZegoLiveAudioRoomRole.speaker) {
            return Padding(
              padding: const EdgeInsets.fromLTRB(10, 0, 10, 0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  giftButton(),
                  const SizedBox(width: 10),
                  leaveSeatButton(),
                  const SizedBox(width: 10),
                  micorphoneButton(),
                ],
              ),
            );
          } else {
            return Padding(
              padding: const EdgeInsets.fromLTRB(10, 0, 10, 0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.start,
                children: [
                  giftButton(),
                  const SizedBox(width: 10),
                  requestTakeSeatButton(),
                ],
              ),
            );
          }
        });
  }

  Widget lockSeatButton() {
    return ElevatedButton(
        onPressed: () => ZegoLiveAudioRoomManager().lockSeat(widget.roomID),
        child: const Icon(Icons.lock));
  }

  Widget requestMemberButton() {
    return ValueListenableBuilder(
      valueListenable: ZEGOSDKManager().zimService.roomRequestMapNoti,
      builder: (context, Map<String, dynamic> requestMap, child) {
        final requestList = requestMap.values.toList();
        return Badge(
            smallSize: 12,
            isLabelVisible: requestList.isNotEmpty,
            child: child);
      },
      child: ElevatedButton(
        onPressed: () => RoomRequestListView.showBasicModalBottomSheet(context),
        child: const Icon(Icons.link),
      ),
    );
  }

  Widget micorphoneButton() {
    return BlocBuilder<LiveKitAudioCubit, LiveKitAudioState>(
      builder: (context, state) {
        final micIsOn = state.micOn;
        return ElevatedButton(
          onPressed: () =>
              context.read<LiveKitAudioCubit>().toggleMic(!micIsOn),
          child: micIsOn ? const Icon(Icons.mic) : const Icon(Icons.mic_off),
        );
      },
    );
  }

  Widget requestTakeSeatButton() {
    return ElevatedButton(
      onPressed: () {
        if (!isApplyStateNoti.value) {
          final senderMap = {
            'room_request_type': RoomRequestType.audienceApplyToBecomeCoHost
          };
          ZEGOSDKManager()
              .zimService
              .sendRoomRequest(
                  ZegoLiveAudioRoomManager().hostUserNoti.value?.iduser ?? '',
                  jsonEncode(senderMap))
              .then((value) {
            isApplyStateNoti.value = true;
            currentRequestID = value.requestID;
          });
        } else {
          if (currentRequestID != null) {
            ZEGOSDKManager()
                .zimService
                .cancelRoomRequest(currentRequestID ?? '')
                .then((value) {
              isApplyStateNoti.value = false;
              currentRequestID = null;
            });
          }
        }
      },
      child: ValueListenableBuilder<bool>(
        valueListenable: isApplyStateNoti,
        builder: (context, isApply, _) {
          return AutoSizeText(
              isApply ? 'Cancel Application' : 'Apply Take Seat');
        },
      ),
    );
  }

  Widget leaveSeatButton() {
    return ElevatedButton(
        onPressed: () {
          for (final element in ZegoLiveAudioRoomManager().seatList) {
            if (element.currentUser.value?.iduser ==
                ZEGOSDKManager().currentUser!.iduser) {
              ZegoLiveAudioRoomManager()
                  .leaveSeat(element.seatIndex)
                  .then((value) {
                ZegoLiveAudioRoomManager().roleNoti.value =
                    ZegoLiveAudioRoomRole.audience;
                isApplyStateNoti.value = false;
                // LiveKit: ensure mic is off when leaving seat
                try {
                  context.read<LiveKitAudioCubit>().toggleMic(false);
                } catch (_) {}
              });
            }
          }
        },
        child: const AutoSizeText('Leave Seat'));
  }

  Widget leaveButton() {
    return GestureDetector(
      onTap: () {
        Navigator.pop(context);
      },
      child: SizedBox(
        width: 40,
        height: 40,
        child: Image.asset('assets/icons/top_close.png'),
      ),
    );
  }

  void takeSeatResult() {}

  void showRemoveSpeakerAndKitOutSheet(
      BuildContext context, UserEntity targetUser) {
    showModalBottomSheet(
      barrierColor: Colors.transparent,
      context: context,
      builder: (BuildContext context) {
        return Wrap(
          children: <Widget>[
            ListTile(
              title: const AutoSizeText('remove speaker',
                  textAlign: TextAlign.center),
              onTap: () {
                Navigator.pop(context);
                ZegoLiveAudioRoomManager()
                    .removeSpeakerFromSeat(targetUser.iduser);
              },
            ),
            ListTile(
              title: AutoSizeText(
                  targetUser.isMicOnNotifier.value
                      ? 'mute speaker'
                      : 'unMute speaker',
                  textAlign: TextAlign.center),
              onTap: () {
                Navigator.pop(context);
                ZegoLiveAudioRoomManager().muteSpeaker(
                    targetUser.iduser, targetUser.isMicOnNotifier.value);
              },
            ),
            ListTile(
              title: const AutoSizeText('kick out user',
                  textAlign: TextAlign.center),
              onTap: () {
                Navigator.pop(context);
                ZegoLiveAudioRoomManager().kickOutRoom(targetUser.iduser);
              },
            ),
          ],
        );
      },
    );
  }

  int getLocalUserSeatIndex() {
    for (final element in ZegoLiveAudioRoomManager().seatList) {
      if (element.currentUser.value?.iduser ==
          ZEGOSDKManager().currentUser!.iduser) {
        return element.seatIndex;
      }
    }
    return -1;
  }

  // zim listener
  void onInComingRoomRequest(OnInComingRoomRequestReceivedEvent event) {}

  void onInComingRoomRequestCancelled(
      OnInComingRoomRequestCancelledEvent event) {}

  void onInComingRoomRequestTimeOut() {}

  void onOutgoingRoomRequestRejected(OnOutgoingRoomRequestRejectedEvent event) {
    isApplyStateNoti.value = false;
    currentRequestID = null;
  }

  void onExpressRoomStateChanged(ZegoRoomStateEvent event) {}

  void onZIMRoomStateChanged(ZIMServiceRoomStateChangedEvent event) {
    debugAppLogger.debug('AudioRoomPage:onZIMRoomStateChanged: $event');
    if ((event.event != ZIMRoomEvent.success) &&
        (event.state != ZIMRoomState.connected)) {}
    if (event.state == ZIMRoomState.disconnected) {
      Navigator.pop(context);
    }
  }

  void onZIMConnectionStateChanged(
      ZIMServiceConnectionStateChangedEvent event) {
    debugAppLogger.debug('AudioRoomPage:onZIMConnectionStateChanged: $event');

    if (event.state == ZIMConnectionState.disconnected) {
      Navigator.pop(context);
    }
  }
}
