// import removed: no active usages in this file

// List<ElementEntity> elements = [
//   ElementEntity(
//     id: 4012,
//     imgElement: 'assets/frames_Gif/frame 4.gif',
//     price: "800",
//     date: 3,
//     linkPath: 'assets/frames_Gif/frame 4.gif',
//     elementName: '',
//     type: 'frame',
//     buy: false,
//   ),
//   ElementEntity(
//     id: 4013,
//     imgElement: 'assets/frames_Gif/frame 5.gif',
//     price: "800",
//     date: 3,
//     linkPath: 'assets/frames_Gif/frame 5.gif',
//     elementName: '',
//     type: 'frame',
//     buy: false,
//   ),
//   ElementEntity(
//     id: 4011,
//     imgElement: 'assets/frames_Gif/frame 3.gif',
//     price: "1500",
//     date: 3,
//     linkPath: 'assets/frames_Gif/frame 3.gif',
//     elementName: '',
//     type: 'frame',
//     buy: false,
//   ),
// ];
//////////////////////////////////////

//   ElementEntity(
//     id: 4003,
//     img: 'assets/frames_images/frame 7_000.png',
//     price: 500,
//     date: 3,
//     linkPath: 'assets/frames_svga/frame 7.svga',
//     elementName: '',
//     type: 'frame',
//     buy: true,
//   ),

//   ElementEntity(
//     id: 4004,
//     img: 'assets/frames_images/frame 8_000.png',
//     price: 500,
//     date: 3,
//     linkPath: 'assets/frames_svga/frame 8.svga',
//     elementName: '',
//     type: 'frame',
//     buy: true,
//   ),

//   ElementEntity(
//     id: 4005,
//     img: 'assets/frames_images/frame 9_000.png',
//     price: 500,
//     date: 3,
//     linkPath: 'assets/frames_svga/frame 9.svga',
//     type: 'frame',
//     buy: true,
//     elementName: '',
//   ),

//   ElementEntity(
//     id: 4007,
//     img: 'assets/frames_images/frame 12_000.png',
//     price: 500,
//     date: 3,
//     linkPath: 'assets/frames_svga/frame 12.svga',
//     elementName: '',
//     type: 'frame',
//     buy: true,
//   ),

//   // ElementEntity(
//   //   id: 4009,
//   //   img: 'assets/frames_Gif/frame 1.gif',
//   //   price: 800,
//   //   date: 3,
//   //   linkPath: 'assets/frames_Gif/frame 1.gif',
//   //   elementName: 'frame 10',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 4010,
//   //   img: 'assets/frames_Gif/frame 2.gif',
//   //   price: 800,
//   //   date: 3,
//   //   linkPath: 'assets/frames_Gif/frame 2.gif',
//   //   elementName: 'frame 11',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 4014,
//   //   img: 'assets/frames_Gif/frame 6.gif',
//   //   price: 900,
//   //   linkPath: 'assets/frames_Gif/frame 6.gif',
//   //   elementName: 'frame 15',
//   //   type: 'frame',
//   // ),
//   ElementEntity(
//     date: 3,
//     buy: false,
//     id: 4015,
//     img: 'assets/frames_images/admin_frame.png',
//     price: 350,
//     linkPath: 'assets/frames_svga/admin-frame.svga',
//     elementName: 'admin',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: true,
//     id: 4016,
//     img: 'assets/frames_images/bang r frame.png',
//     price: 1300,
//     linkPath: 'assets/frames_svga/bang r frame.svga',
//     elementName: '',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: true,
//     id: 4017,
//     img: 'assets/frames_images/frame 1.png',
//     price: 1500,
//     linkPath: 'assets/frames_svga/frame 1.svga',
//     elementName: '',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: true,
//     id: 4018,
//     img: 'assets/frames_images/frame 3.png',
//     price: 1200,
//     linkPath: 'assets/frames_svga/frame 3.svga',
//     elementName: '',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: true,
//     id: 4019,
//     img: 'assets/frames_images/frame_2.png',
//     price: 1200,
//     linkPath: 'assets/frames_svga/frame_2.svga',
//     elementName: '',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: true,
//     id: 4020,
//     img: 'assets/frames_images/ultah.png',
//     price: 750,
//     linkPath: 'assets/frames_svga/ultah.svga',
//     elementName: '',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: false,
//     id: 4021,
//     img: 'assets/frames_images/frame_admin_pink_one.png',
//     price: 350,
//     linkPath: 'assets/frames_svga/frame_admin_pink_one.svga', // manger
//     elementName: 'admin pink',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: false,
//     id: 4022,
//     img: 'assets/frames_images/frame_agency_agent_one.png',
//     price: 350,
//     linkPath: 'assets/frames_svga/frame_agency_agent_one.svga', // agncy
//     elementName: 'agency agent',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: false,
//     id: 4023,
//     img: 'assets/frames_images/frame_manager_one.png',
//     price: 350,
//     linkPath: 'assets/frames_svga/frame_manager_one.svga', // manger
//     elementName: 'manager',
//     type: 'frame',
//   ),

//   ElementEntity(
//     date: 3,
//     buy: false,
//     id: 4024,
//     img: 'assets/vip_frames/svip1.png',
//     price: 350,
//     linkPath: 'assets/vip_frames/svip1.svga',
//     elementName: 'VIP 1',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: false,
//     id: 4025,
//     img: 'assets/vip_frames/svip2.png',
//     price: 350,
//     linkPath: 'assets/vip_frames/svip2.svga',
//     elementName: 'VIP 2',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: false,
//     id: 4026,
//     img: 'assets/vip_frames/svip3.png',
//     price: 350,
//     linkPath: 'assets/vip_frames/svip3.svga',
//     elementName: 'VIP 3',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: false,
//     id: 4027,
//     img: 'assets/vip_frames/svip4.png',
//     price: 350,
//     linkPath: 'assets/vip_frames/svip4.svga',
//     elementName: 'VIP 4',
//     type: 'frame',
//   ),
//   ElementEntity(
//     date: 3,
//     buy: false,
//     id: 4028,
//     img: 'assets/vip_frames/svip5.png',
//     price: 350,
//     linkPath: 'assets/vip_frames/svip5.svga',
//     elementName: 'VIP 5',
//     type: 'frame',
//   ),

//   // Bingkai1
//   ElementEntity(
//     date: 3,
//     buy: true,
//     id: 4029,
//     img: 'assets/frames_images/Bingkai1.png',
//     price: 2000,
//     linkPath: 'assets/frames_svga/Bingkai1.svga',
//     elementName: '',
//     type: 'frame',
//   ),
//   // Bingkai2
//   ElementEntity(
//     date: 3,
//     buy: true,
//     id: 4030,
//     img: 'assets/frames_images/Bingkai2.png',
//     price: 3000,
//     linkPath: 'assets/frames_svga/Bingkai2.svga',
//     elementName: '',
//     type: 'frame',
//   ),
//   // Bingkai3,
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 4031,
//   //   img: 'assets/frames_images/Bingkai3.png',
//   //   price: 4000,
//   //   linkPath: 'assets/frames_svga/Bingkai3.svga',
//   //     elementName: '',

//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 4032,
//   //   img: 'assets/frames_images/Bingkai4.png',
//   //   price: 5000,
//   //   linkPath: 'assets/frames_svga/Bingkai4.svga',
//   //     elementName: '',

//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 4033,
//   //   img: 'assets/frames_images/Bingkai5.png',
//   //   //    assets/frames_images/Bingkai5.png

//   //   price: 6000,
//   //   linkPath: 'assets/frames_svga/Bingkai5.svga',
//   //     elementName: '',

//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   id: 1002,
//   //   img: 'assets/frames_images/frame 5_000.png',
//   //   price: 500,
//   //   date: 3,
//   //   linkPath: 'assets/frames_svga/frame 5.svga',
//   //   elementName: 'frame 1',
//   //   type: 'frame',
//   //   buy: true,
//   // ),
//   // ElementEntity(
//   //   id: 1003,
//   //   img: 'assets/frames_images/frame 6_000.png',
//   //   price: 500,
//   //   date: 3,
//   //   linkPath: 'assets/frames_svga/frame 6.svga',
//   //   elementName: 'frame 2',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 1004,
//   //   img: 'assets/frames_images/frame 7_000.png',
//   //   price: 500,
//   //   date: 3,
//   //   linkPath: 'assets/frames_svga/frame 7.svga',
//   //   elementName: 'frame 3',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 1005,
//   //   img: 'assets/frames_images/frame 8_000.png',
//   //   price: 500,
//   //   date: 3,
//   //   linkPath: 'assets/frames_svga/frame 8.svga',
//   //   elementName: 'frame 4',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 1006,
//   //   img: 'assets/frames_images/frame 9_000.png',
//   //   price: 500,
//   //   date: 3,
//   //   linkPath: 'assets/frames_svga/frame 9.svga',
//   //   elementName: 'frame 5',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 1008,
//   //   img: 'assets/frames_images/frame 11_000.png',
//   //   price: 500,
//   //   date: 3,
//   //   linkPath: 'assets/frames_svga/frame 11.svga',
//   //   elementName: 'frame 7',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 1009,
//   //   img: 'assets/frames_images/frame 12_000.png',
//   //   price: 500,
//   //   date: 3,
//   //   linkPath: 'assets/frames_svga/frame 12.svga',
//   //   elementName: 'frame 8',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 1011,
//   //   img: 'assets/frames_images/frame 14_000.png',
//   //   price: 500,
//   //   date: 3,
//   //   linkPath: 'assets/frames_svga/frame 14.svga',
//   //   elementName: 'frame 9',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 1012,
//   //   img: 'assets/frames_Gif/frame 1.gif',
//   //   price: 800,
//   //   date: 3,
//   //   linkPath: 'assets/frames_Gif/frame 1.gif',
//   //   elementName: 'frame 10',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 1013,
//   //   img: 'assets/frames_Gif/frame 2.gif',
//   //   price: 800,
//   //   date: 3,
//   //   linkPath: 'assets/frames_Gif/frame 2.gif',
//   //   elementName: 'frame 11',
//   //   type: 'frame',
//   //   buy: true,
//   // ),

//   // ElementEntity(
//   //   id: 1014,
//   //   img: 'assets/frames_Gif/frame 3.gif',
//   //   price: 1500,
//   //   date: 3,
//   //   linkPath: 'assets/frames_Gif/frame 3.gif',
//   //   elementName: 'frame 12',
//   //   type: 'frame',
//   //   buy: true,
//   // ),
//   // ElementEntity(
//   //   id: 1015,
//   //   img: 'assets/frames_Gif/frame 4.gif',
//   //   price: 800,
//   //   date: 3,
//   //   linkPath: 'assets/frames_Gif/frame 4.gif',
//   //   elementName: 'frame 13',
//   //   type: 'frame',
//   //   buy: true,
//   // ),
//   // ElementEntity(
//   //   id: 1016,
//   //   img: 'assets/frames_Gif/frame 5.gif',
//   //   price: 800,
//   //   date: 3,
//   //   linkPath: 'assets/frames_Gif/frame 5.gif',
//   //   elementName: 'frame 14',
//   //   type: 'frame',
//   //   buy: true,
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1017,
//   //   img: 'assets/frames_Gif/frame 6.gif',
//   //   price: 900,
//   //   linkPath: 'assets/frames_Gif/frame 6.gif',
//   //   elementName: 'frame 15',
//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 1166,
//   //   img: 'assets/frames_images/admin_frame.png',
//   //   price: 350,
//   //   linkPath: 'assets/frames_svga/admin-frame.svga',
//   //   elementName: 'admin',
//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1167,
//   //   img: 'assets/frames_images/bang r frame.png',
//   //   price: 1300,
//   //   linkPath: 'assets/frames_svga/bang r frame.svga',
//   //   elementName: 'bang',
//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1168,
//   //   img: 'assets/frames_images/frame 1.png',
//   //   price: 1500,
//   //   linkPath: 'assets/frames_svga/frame 1.svga',
//   //   elementName: 'frame',
//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1169,
//   //   img: 'assets/frames_images/frame 3.png',
//   //   price: 1200,
//   //   linkPath: 'assets/frames_svga/frame 3.svga',
//   //   elementName: 'frame',
//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 116,
//   //   img: 'assets/frames_images/frame_2.png',
//   //   price: 1200,
//   //   linkPath: 'assets/frames_svga/frame_2.svga',
//   //   elementName: 'frame_2',
//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 116,
//   //   img: 'assets/frames_images/ultah.png',
//   //   price: 750,
//   //   linkPath: 'assets/frames_svga/ultah.svga',
//   //   elementName: '',
//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 117,
//   //   img: 'assets/frames_images/frame_admin_pink_one.png',
//   //   price: 350,
//   //   linkPath: 'assets/frames_svga/frame_admin_pink_one.svga', // manger
//   //   elementName: 'admin_pink_one',
//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 118,
//   //   img: 'assets/frames_images/frame_agency_agent_one.png',
//   //   price: 350,
//   //   linkPath: 'assets/frames_svga/frame_agency_agent_one.svga', // agncy
//   //   elementName: 'agency_agent _one',
//   //   type: 'frame',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 119,
//   //   img: 'assets/frames_images/frame_manager_one.png',
//   //   price: 350,
//   //   linkPath: 'assets/frames_svga/frame_manager_one.svga', // manger
//   //   elementName: 'manager one',
//   //   type: 'frame',
//   // ),
//   ////////////////////////////////////////////////////////////////////////
//   ////////////////////////////////////////////////////////////////////////
//   ////////////////////////////////////////////////////////////////////////
//   ////////////////////////////////////////////////////////////////////////
//   ////////////////////////////////////////////////////////////////////////
//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 3001,
//   //   img: 'assets/entry_image_svga/panter_.png',
//   //   price: 10000,
//   //   linkPath: 'assets/entry_svga/panter_.svga',
//   //   elementName: 'svip 3',
//   //   type: 'entry',
//   // ), //svip 3
//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 3002,
//   //   img: 'assets/entry_image_svga/naga2_.png',
//   //   price: 10000,
//   //   linkPath: 'assets/entry_svga/naga2_.svga',
//   //   elementName: 'svip 4',
//   //   type: 'entry',
//   // ), //svip 4
//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 3003,
//   //   img: 'assets/entry_image_svga/robot_.png',
//   //   price: 10000,
//   //   linkPath: 'assets/entry_svga/robot_.svga',
//   //   elementName: 'svip 5',
//   //   type: 'entry',
//   // ), //svip 5
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3004,
//   //   img: 'assets/entry_image_svga/transformer.png',
//   //   price: 1000,
//   //   linkPath: 'assets/entry_svga/transformer.svga',
//   //   elementName: 'transformer',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3005,
//   //   img: 'assets/entry_image_svga/yellow car.png',
//   //   price: 999,
//   //   linkPath: 'assets/entry_svga/yellow car.svga',
//   //   elementName: 'yellow car',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3006,
//   //   img: 'assets/entry_image_svga/bmw i8.png',
//   //   price: 500,
//   //   linkPath: 'assets/entry_svga/bmw i8.svga',
//   //   elementName: 'bmw i8',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3007,
//   //   img: 'assets/entry_image_svga/red motobike.png',
//   //   price: 700,
//   //   linkPath: 'assets/entry_svga/red motobike.svga',
//   //   elementName: 'red motobike',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3008,
//   //   img: 'assets/entry_image_svga/rolls royce.png',
//   //   price: 400,
//   //   linkPath: 'assets/entry_svga/rolls royce.svga',
//   //   elementName: 'rolls royce',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3009,
//   //   img: 'assets/entry_image_svga/hummer_.png',
//   //   price: 900,
//   //   linkPath: 'assets/entry_svga/hummer_.svga',
//   //   elementName: 'hummer_',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3010,
//   //   img: 'assets/entry_image_svga/blue car.png',
//   //   price: 1500,
//   //   linkPath: 'assets/entry_svga/blue car.svga',
//   //   elementName: 'blue car',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3011,
//   //   img: 'assets/entry_image_svga/blue atv.png',
//   //   price: 700,
//   //   linkPath: 'assets/entry_svga/blue atv.svga',
//   //   elementName: 'blue atv',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3012,
//   //   img: 'assets/entry_image_svga/black car.png',
//   //   price: 600,
//   //   linkPath: 'assets/entry_svga/black car.svga',
//   //   elementName: 'black car',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3013,
//   //   img: 'assets/entry_image_svga/black sport car.png',
//   //   price: 350,
//   //   linkPath: 'assets/entry_svga/black sport car.svga',
//   //   elementName: 'black sport car',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 3014,
//   //   img: 'assets/entry_image_svga/yellow car0.png',
//   //   price: 350,
//   //   linkPath: 'assets/entry_svga/yellow car0.svga',
//   //   elementName: 'yellow car0',
//   //   type: 'entry',
//   // ),
//   ///////////////////////////////////////////////////////
//   ///////////////////////////////////////////////////////
//   ///////////////////////////////////////////////////////
//   ElementEntity(
//     fileDuration: const Duration(seconds: 4),
//     date: 3,
//     buy: false,
//     id: 3001,
//     img: 'assets/entry_image_svga/panter_.png',
//     price: 10000,
//     linkPath: 'assets/entry_svga/panter_.svga',
//     elementName: 'svip 3',
//     type: 'entry',
//   ), //svip 3
//   ElementEntity(
//     fileDuration: const Duration(seconds: 8),
//     date: 3,
//     buy: false,
//     id: 3002,
//     img: 'assets/entry_image_svga/naga2_.png',
//     price: 10000,
//     linkPath: 'assets/entry_svga/naga2_.svga',
//     elementName: 'svip 4',
//     type: 'entry',
//   ), //svip 4
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: false,
//     id: 3003,
//     img: 'assets/entry_image_svga/robot_.png',
//     price: 10000,
//     linkPath: 'assets/entry_svga/robot_.svga',
//     elementName: 'svip 5',
//     type: 'entry',
//   ), //svip 5

//   // ///////////////////////////////////////////////////////
//   ///////////////////////////////////////////////////////
//   ///////////////////////////////////////////////////////
//   ElementEntity(
//     fileDuration: const Duration(seconds: 13),
//     date: 3,
//     buy: true,
//     id: 3004,
//     img: 'assets/entry_image_svga/transformer.png',
//     price: 1000,
//     linkPath: 'assets/entry_svga/transformer.svga',
//     elementName: 'transformer',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 5),
//     date: 3,
//     buy: true,
//     id: 3005,
//     img: 'assets/entry_image_svga/yellow car.png',
//     price: 999,
//     linkPath: 'assets/entry_svga/yellow car.svga',
//     elementName: 'yellow car',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3006,
//     img: 'assets/entry_image_svga/bmw i8.png',
//     price: 500,
//     linkPath: 'assets/entry_svga/bmw i8.svga',
//     elementName: 'bmw i8',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3007,
//     img: 'assets/entry_image_svga/red motobike.png',
//     price: 700,
//     linkPath: 'assets/entry_svga/red motobike.svga',
//     elementName: 'red motobike',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3008,
//     img: 'assets/entry_image_svga/rolls royce.png',
//     price: 400,
//     linkPath: 'assets/entry_svga/rolls royce.svga',
//     elementName: 'rolls royce',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3009,
//     img: 'assets/entry_image_svga/hummer_.png',
//     price: 900,
//     linkPath: 'assets/entry_svga/hummer_.svga',
//     elementName: 'hummer_',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3010,
//     img: 'assets/entry_image_svga/blue car.png',
//     price: 1500,
//     linkPath: 'assets/entry_svga/blue car.svga',
//     elementName: 'blue car',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3011,
//     img: 'assets/entry_image_svga/blue atv.png',
//     price: 700,
//     linkPath: 'assets/entry_svga/blue atv.svga',
//     elementName: 'blue atv',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3012,
//     img: 'assets/entry_image_svga/black car.png',
//     price: 600,
//     linkPath: 'assets/entry_svga/black car.svga',
//     elementName: 'black car',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3013,
//     img: 'assets/entry_image_svga/black sport car.png',
//     price: 350,
//     linkPath: 'assets/entry_svga/black sport car.svga',
//     elementName: 'black sport car',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3014,
//     img: 'assets/entry_image_svga/yellow car0.png',
//     price: 350,
//     linkPath: 'assets/entry_svga/yellow car0.svga',
//     elementName: 'yellow car0',
//     type: 'entry',
//   ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 1054,
//   //   img: AssetsData.gift,
//   //   price: 10000,
//   //   linkPath: 'assets/entry_svga/panter_.svga',
//   //   elementName: 'svip 3',
//   //   type: 'entry',
//   // ), //svip 3
//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 1052,
//   //   img: AssetsData.gift,
//   //   price: 10000,
//   //   linkPath: 'assets/entry_svga/naga2_.svga',
//   //   elementName: 'svip 4',
//   //   type: 'entry',
//   // ), //svip 4

//   // ElementEntity(
//   //   date: 3,
//   //   buy: false,
//   //   id: 1057,
//   //   img: AssetsData.gift,
//   //   price: 10000,
//   //   linkPath: 'assets/entry_svga/robot_.svga',
//   //   elementName: 'svip 5',
//   //   type: 'entry',
//   // ), //svip 5 ,

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1049,
//   //   img: 'assets/entry_image_svga/transformer.png',
//   //   price: 1000,
//   //   linkPath: 'assets/entry_svga/transformer.svga',
//   //   elementName: 'transformer',
//   //   type: 'entry',
//   // ),

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1055,
//   //   img: 'assets/entry_image_svga/yellow car.png',
//   //   price: 999,
//   //   linkPath: 'assets/entry_svga/yellow car.svga',
//   //   elementName: 'yellow car',
//   //   type: 'entry',
//   // ),

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1066,
//   //   img: 'assets/entry_image_svga/bmw i8.png',
//   //   price: 500,
//   //   linkPath: 'assets/entry_svga/bmw i8.svga',
//   //   elementName: 'bmw i8',
//   //   type: 'entry',
//   // ),

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1070,
//   //   img: 'assets/entry_image_svga/red motobike.png',
//   //   price: 700,
//   //   linkPath: 'assets/entry_svga/red motobike.svga',
//   //   elementName: 'red motobike',
//   //   type: 'entry',
//   // ),

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1071,
//   //   img: 'assets/entry_image_svga/rolls royce.png',
//   //   price: 400,
//   //   linkPath: 'assets/entry_svga/rolls royce.svga',
//   //   elementName: 'rolls royce',
//   //   type: 'entry',
//   // ),

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1044,
//   //   img: AssetsData.gift,
//   //   price: 900,
//   //   linkPath: 'assets/entry_svga/hummer_.svga',
//   //   elementName: 'hummer_',
//   //   type: 'entry',
//   // ),

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1065,
//   //   img: 'assets/entry_image_svga/blue car.png',
//   //   price: 1500,
//   //   linkPath: 'assets/entry_svga/blue car.svga',
//   //   elementName: 'blue car',
//   //   type: 'entry',
//   // ),

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1064,
//   //   img: 'assets/entry_image_svga/blue atv.png',
//   //   price: 700,
//   //   linkPath: 'assets/entry_svga/blue atv.svga',
//   //   elementName: 'blue atv',
//   //   type: 'entry',
//   // ),

//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1062,
//   //   img: 'assets/entry_image_svga/black car.png',
//   //   price: 600,
//   //   linkPath: 'assets/entry_svga/black car.svga',
//   //   elementName: 'black car',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1063,
//   //   img: 'assets/entry_image_svga/black sport car.png',
//   //   price: 350,
//   //   linkPath: 'assets/entry_svga/black sport car.svga',
//   //   elementName: 'black sport car',
//   //   type: 'entry',
//   // ),
//   // ElementEntity(
//   //   date: 3,
//   //   buy: true,
//   //   id: 1164,
//   //   img: 'assets/entry_image_svga/yellow car0.png',
//   //   price: 350,
//   //   linkPath: 'assets/entry_svga/yellow car0.svga',
//   //   elementName: 'yellow car0',
//   //   type: 'entry',
//   // ),
// ];
