import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:lklk/core/utils/logger.dart';

import '../../../utils/zegocloud_token.dart';
import '../../../zego_live_streaming_manager.dart';
import '../../../zego_sdk_key_center.dart';
import '../normal/live_command.dart';

const _roomControllerTag = 'ZegoSwipingRoomController';

class ZegoSwipingRoomController {
  final _data = ZegoSwipingRoomControllerData();
  var roomCommandsNotifier =
      ValueNotifier<Map<String, ZegoLivePageCommand>>({});

  ZegoLiveStreamingManager? liveStreamingManager;

  void init({
    required ValueNotifier<Map<String, ZegoLivePageCommand>>
        roomCommandsNotifier,
    required ZegoLiveStreamingManager liveStreamingManager,
  }) {
    if (_data.init) {
      AppLogger.debug('room controller, init before', tag: _roomControllerTag);
      return;
    }

    this.roomCommandsNotifier = roomCommandsNotifier;
    this.liveStreamingManager = liveStreamingManager;

    AppLogger.debug('room controller, init', tag: _roomControllerTag);

    _data
      ..init = true
      ..roomLoginNotifier ??= ZegoRoomLoginNotifier()
      ..roomLogoutNotifier ??= ZegoRoomLogoutNotifier();

    _data.roomLogoutNotifier?.notifier.addListener(_onLogoutRoomStateChanged);
    _data.roomLoginNotifier?.notifier.addListener(_onLoginRoomStateChanged);

    _data.currentRoomLoginDone.addListener(_onCurrentRoomLoginStateUpdated);
    _data.currentRoomLogoutDone.addListener(_onCurrentRoomLogoutStateUpdated);
  }

  void uninit() {
    if (!_data.init) {
      AppLogger.debug('room controller, not need uninit',
          tag: _roomControllerTag);

      return;
    }

    AppLogger.debug('room controller, uninit', tag: _roomControllerTag);

    _data.init = false;

    _data.roomLoginNotifier?.notifier.removeListener(_onLoginRoomStateChanged);
    _data.roomLogoutNotifier?.notifier
        .removeListener(_onLogoutRoomStateChanged);
    _data.currentRoomLoginDone.removeListener(_onCurrentRoomLoginStateUpdated);
    _data.currentRoomLogoutDone
        .removeListener(_onCurrentRoomLogoutStateUpdated);

    if (currentRoomID.isNotEmpty) {
      liveStreamingManager?.leaveRoom();
    }

    liveStreamingManager = null;
  }

  String get currentRoomID => _data.currentRoomID;

  ZIMService get zimService => ZEGOSDKManager().zimService;

  ExpressService get expressService => ZEGOSDKManager().expressService;

  set currentRoomID(String value) {
    AppLogger.debug('room controller, set current room id:$value',
        tag: _roomControllerTag);
    _data.currentRoomID = value;
  }

  Future<bool> joinRoom(String roomID) async {
    if (roomID.isEmpty) {
      AppLogger.debug('room controller, room id $currentRoomID is empty',
          tag: _roomControllerTag);
      return false;
    }

    if (roomID == _data.currentRoomID) {
      AppLogger.debug('room controller, current room id $currentRoomID is same',
          tag: _roomControllerTag);
      return false;
    }

    if (_data.currentRoomID.isNotEmpty && !_data.currentRoomLoginDone.value) {
      AppLogger.debug(
        'room $currentRoomID is not login done, pending room id:$roomID',
        tag: _roomControllerTag,
      );

      _data.pendingRoomID = roomID;
      return false;
    }
    if (!_data.currentRoomLogoutDone.value) {
      AppLogger.debug(
        'room $currentRoomID is not logout done, pending room id:$roomID',
        tag: _roomControllerTag,
      );

      _data.pendingRoomID = roomID;
      return false;
    }

    currentRoomID = roomID;
    _data.currentRoomLoginDone.value = false;
    _data.roomLoginNotifier?.resetCheckingData(currentRoomID);

    return _joinRoom();
  }

  Future<bool> _joinRoom() async {
    String? token;
    if (kIsWeb) {
      // ! ** Warning: ZegoTokenUtils is only for use during testing. When your application goes live,
      // ! ** tokens must be generated by the server side. Please do not generate tokens on the client side!
      token = ZegoTokenUtils.generateToken(
        SDKKeyCenter.appID,
        SDKKeyCenter.serverSecret,
        ZEGOSDKManager().currentUser!.iduser,
      );
    }

    roomCommandsNotifier.value[currentRoomID]?.registerEvent();

    return ZEGOSDKManager()
        .loginRoom(_data.currentRoomID, ZegoScenario.Broadcast, token: token)
        .then(
      (value) {
        if (value.errorCode != 0) {
          AppLogger.error('Login room failed: ${value.errorCode}',
              tag: _roomControllerTag);
        }

        return value.errorCode == 0;
      },
    );
  }

  Future<bool> switchRoom(String roomID) async {
    if (roomID == _data.currentRoomID) {
      AppLogger.debug('room controller, room id $currentRoomID is empty',
          tag: _roomControllerTag);
      return true;
    }

    if (_data.currentRoomLoginDone.value) {
      AppLogger.debug(
          'room controller, previous room login, leave pending $roomID',
          tag: _roomControllerTag);
      _data.pendingRoomID = roomID;

      return leaveRoom();
    } else if (_data.currentRoomLogoutDone.value) {
      AppLogger.debug('room controller, switch to $roomID',
          tag: _roomControllerTag);

      return joinRoom(roomID);
    }

    AppLogger.debug('room controller, switch pending $roomID',
        tag: _roomControllerTag);
    _data.pendingRoomID = roomID;

    return true;
  }

  Future<bool> leaveRoom() async {
    if (!_data.currentRoomLoginDone.value) {
      AppLogger.debug('room controller, $currentRoomID not login done',
          tag: _roomControllerTag);

      return false;
    }

    AppLogger.debug('room controller, $currentRoomID leave',
        tag: _roomControllerTag);

    _data.roomLogoutNotifier?.resetCheckingData(currentRoomID);
    _data.currentRoomLogoutDone.value = false;

    roomCommandsNotifier.value[currentRoomID]?.unregisterEvent();

    await liveStreamingManager?.leaveRoom();

    return true;
  }
}

class ZegoSwipingRoomControllerData {
  bool init = false;

  /// pending room id if try switch room in join process
  String pendingRoomID = '';

  ///
  String currentRoomID = '';
  var currentRoomLoginDone = ValueNotifier<bool>(false);
  var currentRoomLogoutDone = ValueNotifier<bool>(true);

  ///
  ZegoRoomLoginNotifier? roomLoginNotifier;
  ZegoRoomLogoutNotifier? roomLogoutNotifier;
}

extension ZegoSwipingRoomControllerEvent on ZegoSwipingRoomController {
  void _onLoginRoomStateChanged() {
    final expressDone = expressService.currentRoomID == currentRoomID &&
        ZegoRoomStateChangedReason.Logined == expressService.currentRoomState;

    AppLogger.debug(
      'room controller, swiping page, on room state changed, '
      'target room id:$currentRoomID, '
      'express room id:${expressService.currentRoomID}, '
      'express room state:${expressService.currentRoomState}, ',
      tag: _roomControllerTag,
    );

    final zimDone = zimService.currentRoomID == currentRoomID &&
        ZIMRoomState.connected == zimService.currentRoomState;
    AppLogger.debug(
      'room controller, swiping page, on room state changed, '
      'ZIM room id:${zimService.currentRoomID}, '
      'ZIM room state:${zimService.currentRoomState},',
      tag: _roomControllerTag,
    );

    AppLogger.debug(
      'swiping page, on room state changed, express done:$expressDone, ZIM done:$zimDone',
      tag: _roomControllerTag,
    );
    if (expressDone && zimDone) {
      _data.currentRoomLoginDone.value = true;
    }
  }

  void _onLogoutRoomStateChanged() {
    AppLogger.debug(
      'swiping loading, room ${_data.roomLogoutNotifier?.checkingRoomID} state changed, logout:${_data.roomLogoutNotifier?.value}',
      tag: _roomControllerTag,
    );

    if (_data.roomLogoutNotifier?.value ?? false) {
      AppLogger.debug(
        'swiping loading, room ${_data.roomLogoutNotifier?.checkingRoomID} had logout..',
        tag: _roomControllerTag,
      );

      _data.currentRoomLogoutDone.value = true;
    }
  }

  Future<void> _onCurrentRoomLoginStateUpdated() async {
    final value = _data.currentRoomLoginDone.value;
    AppLogger.debug(
      'room controller, _onCurrentRoomLoginStateUpdated, ${_data.currentRoomID} $value',
      tag: _roomControllerTag,
    );

    if (!value) {
      return;
    }

    if (_data.pendingRoomID.isNotEmpty) {
      /// pending room, leave & join
      await leaveRoom();
    }
  }

  void _onCurrentRoomLogoutStateUpdated() {
    final value = _data.currentRoomLogoutDone.value;
    AppLogger.debug(
      'room controller, _onCurrentRoomLogoutStateUpdated, ${_data.currentRoomID} $value',
      tag: _roomControllerTag,
    );

    if (!value) {
      return;
    }

    currentRoomID = '';

    if (_data.pendingRoomID.isNotEmpty) {
      final pendingRoomID = _data.pendingRoomID;
      _data.pendingRoomID = '';
      joinRoom(pendingRoomID);
    }
  }
}
