// import 'package:lklk/features/profile_users/domain/entities/elements_entity.dart';

// List<ElementEntity> entyElemntsSvga = [
//   ElementEntity(
//     fileDuration: const Duration(seconds: 4),
//     date: 3,
//     buy: false,
//     id: 3001,
//     img: 'assets/entry_image_svga/panter_.png',
//     price: 10000,
//     linkPath: 'assets/entry_svga/panter_.svga',
//     elementName: 'svip 3',
//     type: 'entry',
//   ), //svip 3
//   ElementEntity(
//     fileDuration: const Duration(seconds: 8),
//     date: 3,
//     buy: false,
//     id: 3002,
//     img: 'assets/entry_image_svga/naga2_.png',
//     price: 10000,
//     linkPath: 'assets/entry_svga/naga2_.svga',
//     elementName: 'svip 4',
//     type: 'entry',
//   ), //svip 4
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: false,
//     id: 3003,
//     img: 'assets/entry_image_svga/robot_.png',
//     price: 10000,
//     linkPath: 'assets/entry_svga/robot_.svga',
//     elementName: 'svip 5',
//     type: 'entry',
//   ), //svip 5
//   ElementEntity(
//     fileDuration: const Duration(seconds: 13),
//     date: 3,
//     buy: true,
//     id: 3004,
//     img: 'assets/entry_image_svga/transformer.png',
//     price: 1000,
//     linkPath: 'assets/entry_svga/transformer.svga',
//     elementName: 'transformer',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 5),
//     date: 3,
//     buy: true,
//     id: 3005,
//     img: 'assets/entry_image_svga/yellow car.png',
//     price: 999,
//     linkPath: 'assets/entry_svga/yellow car.svga',
//     elementName: 'yellow car',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3006,
//     img: 'assets/entry_image_svga/bmw i8.png',
//     price: 500,
//     linkPath: 'assets/entry_svga/bmw i8.svga',
//     elementName: 'bmw i8',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3007,
//     img: 'assets/entry_image_svga/red motobike.png',
//     price: 700,
//     linkPath: 'assets/entry_svga/red motobike.svga',
//     elementName: 'red motobike',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3008,
//     img: 'assets/entry_image_svga/rolls royce.png',
//     price: 400,
//     linkPath: 'assets/entry_svga/rolls royce.svga',
//     elementName: 'rolls royce',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3009,
//     img: 'assets/entry_image_svga/hummer_.png',
//     price: 900,
//     linkPath: 'assets/entry_svga/hummer_.svga',
//     elementName: 'hummer_',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3010,
//     img: 'assets/entry_image_svga/blue car.png',
//     price: 1500,
//     linkPath: 'assets/entry_svga/blue car.svga',
//     elementName: 'blue car',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3011,
//     img: 'assets/entry_image_svga/blue atv.png',
//     price: 700,
//     linkPath: 'assets/entry_svga/blue atv.svga',
//     elementName: 'blue atv',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3012,
//     img: 'assets/entry_image_svga/black car.png',
//     price: 600,
//     linkPath: 'assets/entry_svga/black car.svga',
//     elementName: 'black car',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3013,
//     img: 'assets/entry_image_svga/black sport car.png',
//     price: 350,
//     linkPath: 'assets/entry_svga/black sport car.svga',
//     elementName: 'black sport car',
//     type: 'entry',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     date: 3,
//     buy: true,
//     id: 3014,
//     img: 'assets/entry_image_svga/yellow car0.png',
//     price: 350,
//     linkPath: 'assets/entry_svga/yellow car0.svga',
//     elementName: 'yellow car0',
//     type: 'entry',
//   ),
// ];
