// import 'package:lklk/features/profile_users/domain/entities/elements_entity.dart';

// List<ElementEntity> giftsSVGAElements = [
//   ElementEntity(
//     fileDuration: const Duration(seconds: 5),
//     id: 1104,
//     img: 'assets/gifts_image_svga/Bouquet.png',
//     price: 277,
//     linkPath: 'assets/gifts_svga/Bouquet.svga',
//     elementName: 'Bouquet',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 1),
//     id: 1101,
//     img: 'assets/gifts_image_svga/slipper.png',
//     price: 10,
//     linkPath: 'assets/gifts_svga/slipper.svga',
//     elementName: 'slipper',
//     type: 'lucky',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 2),
//     id: 1102,
//     img: 'assets/gifts_image_svga/frut juico.png',
//     price: 50,
//     linkPath: 'assets/gifts_svga/fruit juice.svga',
//     elementName: 'fruit juice',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 2),
//     id: 1103,
//     img: 'assets/gifts_image_svga/sheep.png',
//     price: 33,
//     linkPath: 'assets/gifts_svga/sheep.svga',
//     elementName: 'sheep',
//     type: 'lucky',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(milliseconds: 9700),
//     id: 1151,
//     img: 'assets/gifts_image_svga/Yellow Rose.png',
//     price: 499,
//     linkPath: 'assets/gifts_svga/Yellow Rose.svga',
//     elementName: 'Yellow Rose',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 2),
//     id: 1105,
//     img: 'assets/gifts_image_svga/clock-icon.png',
//     price: 500,
//     linkPath: 'assets/gifts_svga/clock.svga',
//     elementName: 'clock',
//     type: 'lucky',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 3),
//     id: 1106,
//     img: 'assets/gifts_image_svga/sheep 1.png',
//     price: 100,
//     linkPath: 'assets/gifts_svga/sheep (1).svga',
//     elementName: 'sheep (1)',
//     type: 'lucky',
//   ),
//   // 1106  --- 100
//   ElementEntity(
//     fileDuration: const Duration(seconds: 3),
//     id: 1107,
//     img: 'assets/gifts_image_svga/rose with love.png',
//     price: 300,
//     linkPath: 'assets/gifts_svga/rose with love.svga',
//     elementName: 'rose with love',
//     type: 'lucky',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 2),
//     id: 1108,
//     img: 'assets/gifts_image_svga/shisha.png',
//     price: 300,
//     linkPath: 'assets/gifts_svga/shisha.svga',
//     elementName: 'shisha',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 4),
//     id: 1109,
//     img: 'assets/gifts_image_svga/coffee.png',
//     price: 666,
//     linkPath: 'assets/gifts_svga/coffee.svga',
//     elementName: 'coffee',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 5),
//     id: 1110,
//     img: 'assets/gifts_image_svga/crown.png',
//     price: 777,
//     linkPath: 'assets/gifts_svga/crown.svga',
//     elementName: 'crown',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     id: 1149,
//     img: 'assets/gifts_image_svga/Rose Boutique.png',
//     price: 266,
//     linkPath: 'assets/gifts_svga/Rose Boutique.svga',
//     elementName: 'Rose Boutique',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 2),
//     id: 1111,
//     img: 'assets/gifts_image_svga/kiss.png',
//     price: 80,
//     linkPath: 'assets/gifts_svga/kiss.svga',
//     elementName: 'kiss',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 11),
//     id: 1112,
//     img: 'assets/gifts_image_svga/diamond(1).png',
//     price: 577,
//     linkPath: 'assets/gifts_svga/diamond(1).svga',
//     elementName: 'diamond(1)',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 3),
//     id: 1113,
//     img: 'assets/gifts_image_svga/mic-icon.png',
//     price: 900,
//     linkPath: 'assets/gifts_svga/mic.svga',
//     elementName: 'mic',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 6),
//     id: 1114,
//     img: 'assets/gifts_image_svga/piano wing.png',
//     price: 977,
//     linkPath: 'assets/gifts_svga/piano wing.svga',
//     elementName: 'piano wing',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 6),
//     id: 1115,
//     img: 'assets/gifts_image_svga/suprem gun.png',
//     price: 888,
//     linkPath: 'assets/gifts_svga/suprem gun.svga',
//     elementName: 'suprem gun',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 14),
//     id: 1150,
//     img: 'assets/gifts_image_svga/Valentine.png',
//     price: 1100,
//     linkPath: 'assets/gifts_svga/Valentine.svga',
//     elementName: 'Valentine',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     id: 1145,
//     img: 'assets/gifts_image_svga/love car.png',
//     price: 1999,
//     linkPath: 'assets/gifts_svga/love car.svga',
//     elementName: 'love car',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 7),
//     id: 1116,
//     img: 'assets/gifts_image_svga/lamp.png',
//     price: 1200,
//     linkPath: 'assets/gifts_svga/lamp.svga',
//     elementName: 'lamp',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 5),
//     id: 1117,
//     img: 'assets/gifts_image_svga/rock.png',
//     price: 1000,
//     linkPath: 'assets/gifts_svga/rock.svga',
//     elementName: 'rock',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 6),
//     id: 1118,
//     img: 'assets/gifts_image_svga/ring 4.png',
//     price: 100,
//     linkPath: 'assets/gifts_svga/ring 4.svga',
//     elementName: 'ring 4',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 7),
//     id: 1119,
//     img: 'assets/gifts_image_svga/top live.png',
//     price: 1250,
//     linkPath: 'assets/gifts_svga/top live.svga',
//     elementName: 'top live',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 6),
//     id: 1120,
//     img: 'assets/gifts_image_svga/dragon.png',
//     price: 1075,
//     linkPath: 'assets/gifts_svga/dragon.svga',
//     elementName: 'dragon',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     id: 1146,
//     img: 'assets/gifts_image_svga/Love Flower.png',
//     price: 999,
//     linkPath: 'assets/gifts_svga/Love Flower.svga',
//     elementName: 'Love Flower',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     id: 1121,
//     img: 'assets/gifts_image_svga/pink car_2.png',
//     price: 3800,
//     linkPath: 'assets/gifts_svga/pink car_2.svga',
//     elementName: 'pink car 2',
//     type: 'couple',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 7),
//     id: 1122,
//     img: 'assets/gifts_image_svga/castle 2.png',
//     price: 1377,
//     linkPath: 'assets/gifts_svga/castle_2.svga',
//     elementName: 'castle_2',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 9),
//     id: 1123,
//     img: 'assets/gifts_image_svga/gunung.png',
//     price: 1377,
//     linkPath: 'assets/gifts_svga/gunung_.svga',
//     elementName: 'gunung_',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 26),
//     id: 1148,
//     img: 'assets/gifts_image_svga/Ramadan Eid Mubarak.png',
//     price: 1577,
//     linkPath: 'assets/gifts_svga/Ramadan Eid Mubarak.svga',
//     elementName: 'Ramadan Eid Mubarak',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 5),
//     id: 1124,
//     img: 'assets/gifts_image_svga/car_0.png',
//     price: 1177,
//     linkPath: 'assets/gifts_svga/car_0.svga',
//     elementName: 'car_0',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 6),
//     id: 1125,
//     img: 'assets/gifts_image_svga/dagger 1.png',
//     price: 1777,
//     linkPath: 'assets/gifts_svga/dagger(1).svga',
//     elementName: 'dagger(1)',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 11),
//     id: 1126,
//     img: 'assets/gifts_image_svga/halloween.png',
//     price: 1900,
//     linkPath: 'assets/gifts_svga/halloween.svga',
//     elementName: 'halloween',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     id: 1127,
//     img: 'assets/gifts_image_svga/plane1.png',
//     price: 2000,
//     linkPath: 'assets/gifts_svga/plane1.svga',
//     elementName: 'plane1',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 6),
//     id: 1128,
//     img: 'assets/gifts_image_svga/mermaid1.png',
//     price: 2277,
//     linkPath: 'assets/gifts_svga/Mermaid(1).svga',
//     elementName: 'Mermaid(1)',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 3),
//     id: 1129,
//     img: 'assets/gifts_image_svga/kursi raja.png',
//     price: 400,
//     linkPath: 'assets/gifts_svga/kursi raja_.svga',
//     elementName: 'kursi raja_',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 20),
//     id: 1147,
//     img: 'assets/gifts_image_svga/Luxuries Villa.png',
//     price: 15666,
//     linkPath: 'assets/gifts_svga/Luxuries Villa.svga',
//     elementName: 'Luxuries Villa',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 11),
//     id: 1130,
//     img: 'assets/gifts_image_svga/castil girl.png',
//     price: 2777,
//     linkPath: 'assets/gifts_svga/castil girl .svga',
//     elementName: 'castil girl',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     id: 1131,
//     img: 'assets/gifts_image_svga/rafce car.png',
//     price: 1866,
//     linkPath: 'assets/gifts_svga/rafce car.svga',
//     elementName: 'rafce car',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 6),
//     id: 1132,
//     img: 'assets/gifts_image_svga/love plane.png',
//     price: 8777,
//     linkPath: 'assets/gifts_svga/love plane.svga',
//     elementName: 'love plane',
//     type: 'couple',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     id: 1133,
//     img: 'assets/gifts_image_svga/king.png',
//     price: 29999,
//     linkPath: 'assets/gifts_svga/king.svga',
//     elementName: 'king',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(milliseconds: 5800),
//     id: 1134,
//     img: 'assets/gifts_image_svga/villa com.png',
//     price: 7777,
//     linkPath: 'assets/gifts_svga/villa com.svga',
//     elementName: 'villa com',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 9),
//     id: 1135,
//     img: 'assets/gifts_image_svga/love swan.png',
//     price: 14888,
//     linkPath: 'assets/gifts_svga/love swan.svga',
//     elementName: 'love swan',
//     type: 'couple',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     id: 1136,
//     img: 'assets/gifts_image_svga/rocket2.png',
//     price: 69999,
//     linkPath: 'assets/gifts_svga/rocket2.svga',
//     elementName: 'rocket2',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 10),
//     id: 1137,
//     img: 'assets/gifts_image_svga/love castle.png',
//     price: 13777,
//     linkPath: 'assets/gifts_svga/love castle.svga',
//     elementName: 'love castle',
//     type: 'couple',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 11),
//     id: 1138,
//     img: 'assets/gifts_image_svga/ufo.png',
//     price: 17777,
//     linkPath: 'assets/gifts_svga/ufo.svga',
//     elementName: 'ufo',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 6),
//     id: 1139,
//     img: 'assets/gifts_image_svga/ghost_.png',
//     price: 5777,
//     linkPath: 'assets/gifts_svga/ghost_.svga',
//     elementName: 'ghost',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 6),
//     id: 1140,
//     img: 'assets/gifts_image_svga/elang.png',
//     price: 25999,
//     linkPath: 'assets/gifts_svga/elang_.svga',
//     elementName: 'elang_',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 12),
//     id: 1141,
//     img: 'assets/gifts_image_svga/cars n monster.png',
//     price: 24888,
//     linkPath: 'assets/gifts_svga/cars n monster.svga',
//     elementName: 'cars n monster',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 9),
//     id: 1142,
//     img: 'assets/gifts_image_svga/knight icon.png',
//     price: 29999,
//     linkPath: 'assets/gifts_svga/knight(1).svga',
//     elementName: 'knight(1)',
//     type: 'popular',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 9),
//     id: 1144,
//     img: 'assets/gifts_image_svga/music box.png',
//     price: 37888,
//     linkPath: 'assets/gifts_svga/music box.svga',
//     elementName: 'music box',
//     type: 'couple',
//   ),
//   ElementEntity(
//     fileDuration: const Duration(seconds: 13), //12
//     id: 1143,
//     img: 'assets/gifts_image_svga/dragon ice .png',
//     price: 39999,
//     linkPath: 'assets/gifts_svga/dragon ice .svga',
//     elementName: 'dragon ice',
//     type: 'popular',
//   ),
// ];
//  List<ElementEntity> waves = [
//       ElementEntity(
//         fileDuration: const Duration(seconds: 5),
//         id: 1104,
//         img: '',
//         price: 277,
//         elementName: '',
//         linkPath: 'assets/waves/VIP1.svga',
//         type: 'popular',
//       ),
//       ElementEntity(
//         fileDuration: const Duration(seconds: 5),
//         id: 1104,
//         img: '',
//         price: 277,
//         elementName: '',
//         linkPath: 'assets/waves/VIP2.svga',
//         type: 'popular',
//       ),
//       ElementEntity(
//         fileDuration: const Duration(seconds: 5),
//         id: 1104,
//         img: '',
//         price: 277,
//         elementName: '',
//         linkPath: 'assets/waves/VIP3.svga',
//         type: 'popular',
//       ),
//       ElementEntity(
//         fileDuration: const Duration(seconds: 5),
//         id: 1104,
//         img: '',
//         price: 277,
//         elementName: '',
//         linkPath: 'assets/waves/VIP4.svga',
//         type: 'popular',
//       ),
//       ElementEntity(
//         fileDuration: const Duration(seconds: 5),
//         id: 1104,
//         img: '',
//         price: 277,
//         elementName: '',
//         linkPath: 'assets/waves/VIP5.svga',
//         type: 'popular',
//       ),
//       ElementEntity(
//         fileDuration: const Duration(seconds: 5),
//         id: 1104,
//         img: '',
//         price: 277,
//         elementName: '',
//         linkPath: 'assets/waves/VIP6.svga',
//         type: 'popular',
//       ),
//     ];
